/*
 * Event API
 *
 * The Event API provides functionality related to calendar events and bookings
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using OpenApiGeneratorTesting.Converters;

namespace OpenApiGeneratorTesting.Models
{ 
    /// <summary>
    /// A particular speaker added to an event.
    /// </summary>
    [DataContract]
    public class SpeakerCreate : IEquatable<SpeakerCreate>
    {
        /// <summary>
        /// Gets or Sets EventId
        /// </summary>
        [Required]
        [DataMember(Name="eventId", EmitDefaultValue=false)]
        public SpeakerCreateEventId EventId { get; set; }

        /// <summary>
        /// The unique identifier of the speaker
        /// </summary>
        /// <value>The unique identifier of the speaker</value>
        [Required]
        [DataMember(Name="personId", EmitDefaultValue=false)]
        public string PersonId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SpeakerCreate {\n");
            sb.Append("  EventId: ").Append(EventId).Append("\n");
            sb.Append("  PersonId: ").Append(PersonId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((SpeakerCreate)obj);
        }

        /// <summary>
        /// Returns true if SpeakerCreate instances are equal
        /// </summary>
        /// <param name="other">Instance of SpeakerCreate to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SpeakerCreate other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    EventId == other.EventId ||
                    EventId != null &&
                    EventId.Equals(other.EventId)
                ) && 
                (
                    PersonId == other.PersonId ||
                    PersonId != null &&
                    PersonId.Equals(other.PersonId)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (EventId != null)
                    hashCode = hashCode * 59 + EventId.GetHashCode();
                    if (PersonId != null)
                    hashCode = hashCode * 59 + PersonId.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(SpeakerCreate left, SpeakerCreate right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(SpeakerCreate left, SpeakerCreate right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
